services:
  grafana:
    user: root
    container_name: 'willianmustafa-apiwatchdog-datasource'

    build:
      context: .config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-11.2.0}
        development: ${DEVELOPMENT:-false}
    ports:
      - 3000:3000/tcp
      - 2345:2345/tcp # delve
    security_opt:
      - 'apparmor:unconfined'
      - 'seccomp:unconfined'
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./dist:/var/lib/grafana/plugins/willianmustafa-apiwatchdog-datasource
      - ./provisioning:/etc/grafana/provisioning
      - .:/root/willianmustafa-apiwatchdog-datasource

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.willianmustafa-apiwatchdog-datasource:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: willianmustafa-apiwatchdog-datasource
